spring.application.name=SevaBank

# PostgreSQL
spring.datasource.postgres.jdbc-url=jdbc:postgresql://localhost:5432/sevabankdb
spring.datasource.postgres.username=vishalgautam
spring.datasource.postgres.password=root@123
spring.datasource.postgres.driver-class-name=org.postgresql.Driver

# MySQL
spring.datasource.mysql.jdbc-url=jdbc:mysql://localhost:3306/bank_system
spring.datasource.mysql.username=root
spring.datasource.mysql.password=root@123
spring.datasource.mysql.driver-class-name=com.mysql.jdbc.Driver

# HikariCP
spring.datasource.postgres.hikari.maximum-pool-size=3
spring.datasource.postgres.hikari.minimum-idle=1
spring.datasource.postgres.hikari.connection-timeout=5000

spring.datasource.mysql.hikari.maximum-pool-size=3
spring.datasource.mysql.hikari.minimum-idle=1
spring.datasource.mysql.hikari.connection-timeout=5000